dict_players = {
    "Atlanta": ["Trey", "Young", "Clint", "Capela", "Collins", "Lu Will"],
    "Boston": ["Kemba", "Smart", "Tatum", "Brown"],
    "Brooklyn": ["Durant", "Irving", "Kyrie", "Harden", "Harris"],
    "Charlotte": ["Lamelo", "Terry", "Rozier", "Mo", "Bamba"],
    "Chicago": ["Zack", "Lavine", "Vucevic", "Gucci Mane"],
    "Cleveland": ["Jarrett", "Allen", "Sexton", "Love", "Garland"],
    "Dallas": ["Luka", "Doncic", "KP", "Kristaps", "Porzingus", "Hardaway"],
    "Denver": ["Jokic", "Aaron", "Gordon", "Jamal", "Murray"],
    "Detroit": ["Jerami", "Grant", "Mason", "Plumlee"],
    "Golden State": ["Curry", "Steph", "Kelly", "Oubre", "Draymond", "Green"],
    "Houston": ["Christan", "Wood", "Wall"],
    "Indiana": ["T.J.", "Warren", "Caris", "Levert", "Domantas", "Sabonis"],
    "LA": ["Kahi", "Leonard", "Paul", "George", "PG", "The Claw", "Boogie", 
    "Cousins"],
    "Los Angeles": ["Lebron", "AD", "Davis", "Andre", "Drummond", "Dennis", 
    "Schroder"],
    "Memphis": ["JJ", "Jaren", "Jackson", "Jnoas", "Valanciunas", "Ja", "Morant"],
    "Miami": ["Tyler", "Hero", "Goran", "Dragic", "Jimmy Buckets", "Jimmy",
    "Butler", "Victor", "Oladipo"],
    "Milwaukee": ["Giannis", "Antetokounmpo", "Khris", "Middleton", "Jrue",
    "Holiday", "Drew"],
    "Minnesota": ["D'Angelo", "Russell", "Edwards", "Karl Anthony", "Towns", 
    "cat", "KAT", "Carl Anthony"],
    "New Orleans": ["Zion", "Williamson", "Brandon", "Ingram", "Bledsoe", "IT"],
    "New York": ["Randle", "Julius", "Derrick", "Rose", "Taj", "Quickly", "RJ",
    "Barret"],
    "Oklahoma City": ["SGA", "Shai", "Gilgeous", "Alexander", "Al", "Hortford",
    "Lu", "Dort"],
    "Orlando": ["Wendell", "Carter Jr.", "Jonathan", "Isaac", "Otto", "Porter",
    "Fultz"],
    "Philadelphia": ["Joel", "Embiid", "Ben", "Simmons", "Tobias", "Harris"],
    "Phoenix": ["CP3", "see pea three", "Chris", "Paul", "Devin", "Booker", "D book", 
    "Deandre", "Ayton", "Jay", "Jae", "Crowder", "Mikal", "Bridges"],
    "Portland": ["Dame", "Dolla", "Dame time", "Damian", "Lillard", "CJ", 
    "McCollum", "3j", "Jusuf", "Nurkic", "Melo", "Carlmelo", "Anthony",
    "Norman", "Powell", "Norm"],
    "Sacramento": ["De'Aaron", "Fox", "Buddy", "Hield", "Marvin", "Bagley"],
    "San Antonio": ["DeMar", "DeRozan", "Derrick", "White"],
    "Toronto": ["Kyle", "Lowry", "Pascal", "Siakam", "OG", "Fred"],
    "Utah": ["Mike", "Conley", "Donovan", "Mitchell", "Rudy", "Gobert"],
    "Washington": ["Russell", "Westbrook", "Bradley", "Beal"]
}